"""Report & receipt generation: branded lab report + cash receipt, rendered natively with Qt. Re-exports the former ``report.py`` public API unchanged."""

from __future__ import annotations

# db/render bound here to preserve the report<->render import cycle contract
from .. import db, render
from .constants import (
    ACCENT,
    AMBER,
    ARROW_DOWN,
    ARROW_UP,
    ASSETS,
    BLUE,
    BODY,
    GREEN,
    INTER_TTF,
    RED,
    SLATE,
    TEAL,
    TEAL_DARK,
)
from .content import (
    _contacts,
    _culture_section,
    _g,
    _history_for_item,
    _patient_card,
    _patient_pairs,
    _prev_impression,
    _regs,
    _report_section,
    _signatures,
    _user_display,
    _value_cell,
)
from .export import (
    _make_printer,
    _pdf_target,
    build_receipt_bytes,
    build_report_bytes,
    build_test_page_bytes,
    export_receipt_pdf,
    export_report_pdf,
    print_doc,
    print_receipt,
    print_report,
    print_test_page,
    save_report_pdf,
)
from .formatting import (
    _ONES,
    _TENS,
    _amount_in_words,
    _esc,
    _file_url,
    _flag,
    _flag_arrow,
    _fmt_date,
    _img,
    _method_block,
    _remarks_block,
    _resolve_ref,
    _three,
    _two,
)
from .html import (
    _RECEIPT_CSS,
    _REPORT_CSS,
    _doc,
    _font_face,
    build_receipt_html,
    build_report_html,
)
from .verify import report_fingerprint, verification_code, verify

__all__ = [
    # constants
    "ACCENT",
    "AMBER",
    "ARROW_DOWN",
    "ARROW_UP",
    "ASSETS",
    "BLUE",
    "BODY",
    "GREEN",
    "INTER_TTF",
    "RED",
    "SLATE",
    "TEAL",
    "TEAL_DARK",
    # formatting
    "_ONES",
    "_RECEIPT_CSS",
    # html
    "_REPORT_CSS",
    "_TENS",
    "_amount_in_words",
    # content
    "_contacts",
    "_culture_section",
    "_doc",
    "_esc",
    "_file_url",
    "_flag",
    "_flag_arrow",
    "_fmt_date",
    "_font_face",
    "_g",
    "_history_for_item",
    "_prev_impression",
    "_img",
    # export
    "_make_printer",
    "_method_block",
    "_patient_card",
    "_patient_pairs",
    "_pdf_target",
    "_regs",
    "_remarks_block",
    "_report_section",
    "_resolve_ref",
    "_signatures",
    "_three",
    "_two",
    "_user_display",
    "_value_cell",
    "build_receipt_bytes",
    "build_receipt_html",
    "build_report_bytes",
    "build_report_html",
    "build_test_page_bytes",
    # sibling modules bound for the import-cycle contract (report.db / report.render)
    "db",
    "export_receipt_pdf",
    "export_report_pdf",
    "print_doc",
    "print_receipt",
    "print_report",
    "print_test_page",
    "render",
    # verification (keyed HMAC report code)
    "report_fingerprint",
    "save_report_pdf",
    "verification_code",
    "verify",
]
