"""Where LabDesk's bundled resources (schema.sql, seed.sqlite, assets/) live.

Every resource lookup in the package anchors on `package_root()` rather than on a
module's own `__file__`. This matters for the shipped product:

  * Source / dev runs (and the quick `build_app.sh` host build): no `_embedded_data`
    module exists, so resources are read straight from the package directory.

  * The installed, Nuitka-compiled binary: schema.sql / seed.sqlite / assets are
    BAKED INTO the binary (scripts/gen_embedded.py -> _embedded_data) so nothing
    readable is shipped beside it. SQLite and Qt open these by path, so at import we
    materialise them into one private, 0700, auto-deleted temp dir and point
    `package_root()` there. No install-dir files; nothing to leak.
"""

from __future__ import annotations

import os
from pathlib import Path

try:
    from . import _embedded_data as _emb  # generated by the build; absent in dev
except ImportError:
    _emb = None

_RES: Path | None = None
if _emb is not None:
    import atexit
    import base64
    import shutil
    import tempfile

    _RES = Path(tempfile.mkdtemp(prefix="labdesk-res-"))  # mode 0700 by default
    atexit.register(lambda: shutil.rmtree(_RES, ignore_errors=True))
    (_RES / "schema.sql").write_bytes(base64.b64decode(_emb.SCHEMA_B64))
    (_RES / "seed.sqlite").write_bytes(base64.b64decode(_emb.SEED_B64))
    for _rel, _b64 in _emb.ASSETS.items():
        _dst = _RES / "assets" / _rel
        _dst.parent.mkdir(parents=True, exist_ok=True)
        _dst.write_bytes(base64.b64decode(_b64))


def package_root() -> Path:
    """Directory holding schema.sql, seed.sqlite and assets/.

    Compiled build → the private temp dir the embedded resources were unpacked into.
    Otherwise → LABDESK_RESOURCE_DIR if set, else the labdesk package directory
    (correct for source / host-build runs).
    """
    if _RES is not None:
        return _RES
    env = os.environ.get("LABDESK_RESOURCE_DIR")
    if env:
        return Path(env)
    return Path(__file__).resolve().parent


def schema_file() -> Path:
    return package_root() / "schema.sql"


def seed_db() -> Path:
    return package_root() / "seed.sqlite"
