"""Where LabDesk's bundled resources (schema.sql, seed.sqlite, assets/) live.

In a Nuitka-compiled build, resources are baked into the binary
(scripts/gen_embedded.py -> _embedded_data) and unpacked here into a private,
0700, auto-deleted temp dir; in source/dev runs they're read from the package dir.
"""

from __future__ import annotations

import os
from pathlib import Path

try:
    from . import _embedded_data as _emb  # generated by the build; absent in dev
except ImportError:
    _emb = None

_RES: Path | None = None
if _emb is not None:
    import atexit
    import base64
    import shutil
    import tempfile

    _RES = Path(tempfile.mkdtemp(prefix="labdesk-res-"))
    atexit.register(lambda: shutil.rmtree(_RES, ignore_errors=True))
    (_RES / "schema.sql").write_bytes(base64.b64decode(_emb.SCHEMA_B64))
    (_RES / "seed.sqlite").write_bytes(base64.b64decode(_emb.SEED_B64))
    for _rel, _b64 in _emb.ASSETS.items():
        _dst = _RES / "assets" / _rel
        _dst.parent.mkdir(parents=True, exist_ok=True)
        _dst.write_bytes(base64.b64decode(_b64))


def package_root() -> Path:
    """Directory holding schema.sql, seed.sqlite and assets/."""
    if _RES is not None:
        return _RES
    env = os.environ.get("LABDESK_RESOURCE_DIR")
    if env:
        return Path(env)
    return Path(__file__).resolve().parent


def schema_file() -> Path:
    return package_root() / "schema.sql"


def seed_db() -> Path:
    return package_root() / "seed.sqlite"
